/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   src/vaadin-chart.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.

import {PolymerElement} from '@polymer/polymer/polymer-element.js';

import {FlattenedNodesObserver} from '@polymer/polymer/lib/utils/flattened-nodes-observer.js';

import {beforeNextRender} from '@polymer/polymer/lib/utils/render-status.js';

import {ThemableMixin} from '@vaadin/vaadin-themable-mixin/vaadin-themable-mixin.js';

import {ElementMixin} from '@vaadin/vaadin-element-mixin/vaadin-element-mixin.js';

import {ChartSeriesElement} from './vaadin-chart-series.js';

import {html} from '@polymer/polymer/lib/utils/html-tag.js';

/**
 * `<vaadin-chart>` is a Web Component for creating high quality charts.
 *
 * ### Basic use
 *
 * There are two ways of configuring your `<vaadin-chart>` element: **HTML API**, **JS API** and **JSON API**.
 * Note that you can make use of all APIs in your element.
 *
 * #### Configuring your chart using HTML API
 *
 * `vaadin-chart` has a set of attributes to make it easier for you to customize your chart.
 *
 * ```html
 *  <vaadin-chart title="The chart title" subtitle="The chart subtitle">
 *    <vaadin-chart-series
 *          type="column"
 *          title="The series title"
 *          values="[10,20,30]">
 *    </vaadin-chart-series>
 *  </vaadin-chart>
 * ```
 *
 * > Note that while you can set type for each series individually, for some types, such as `'bar'`, `'gauge'` and `'solidgauge'`, you
 * > have to set it as the default series type on `<vaadin-chart>` in order to work properly.
 *
 * #### Configuring your chart using JS API
 *
 * 1. Set an id for the `<vaadin-chart>` in the template
 * ```html
 *     <vaadin-chart id="mychart"></vaadin-chart>
 * ```
 * 1. Add a function that uses `configuration` property (JS Api) to set chart title, categories and data
 * ```js
 * initChartWithJSApi() {
 *     Polymer.RenderStatus.beforeNextRender(this, () => {
 *        const configuration = this.$.mychart.configuration;
 *        configuration.setTitle({ text: 'The chart title' });
 *        // By default there is one x axis, it is referenced by configuration.xAxis[0].
 *        configuration.xAxis[0].setCategories(['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']);
 *        configuration.addSeries({
 *            type: 'column',
 *            data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]
 *        });
 *     });
 * }
 * ```
 * 1. Call that function from connectedCallback (when the element is added to a document)
 * ```js
 * connectedCallback() {
 *     super.connectedCallback();
 *     this.initChartWithJSApi();
 * }
 * ```
 *
 * #### Configuring your chart using JS JSON API
 *
 * JS JSON API is a simple alternative to the JS API.
 *
 * 1. Set an id for the `<vaadin-chart>` in the template
 * ```html
 *     <vaadin-chart id="mychart"></vaadin-chart>
 * ```
 * 1. Add a function that uses `update` method (JS JSON Api) to set chart title, categories and data
 * ```js
 * initChartWithJSJSONApi() {
 *     this.$.mychart.update({
 *       title: {
 *         text: 'The chart title'
 *       },
 *       subtitle: {
 *         text: 'Subtitle'
 *       },
 *       xAxis: {
 *         categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
 *       },
 *       series: [{
 *         type: 'column',
 *         data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]
 *       }]
 *     });
 * }
 * ```
 * 1. Call that function from connectedCallback (when the element is added to a document)
 * ```js
 * connectedCallback() {
 *     super.connectedCallback();
 *     this.initChartWithJSJSONApi();
 * }
 * ```
 *
 * It should be noted that chart style customization cannot be done via the JS or JSON API.
 * Styling properties in the JSON configuration will be ignored. The following section discusses chart styling.
 *
 *
 * ### CSS Styling
 * Chart appearance is primarily controlled by CSS style rules.
 * A comprehensive list of the supported style classes can be found at
 * https://www.highcharts.com/docs/chart-design-and-style/style-by-css
 *
 *
 * ### Steps for styling a chart
 *
 * 1. Create a theme file (for example `shared-styles.html`). The theme's dom-module must declare `theme-for=vaadin-chart`.
 * 2. Import `vaadin-chart-default-theme.html` and declare `include="vaadin-chart-default-theme"`
 * on the theme module's style tag to customize Chart's default theme. If there are multiple theme
 * modules *only one* of them should declare this `include`.
 * 3. Specify the desired CSS rules in the theme file.
 * 4. If multiple charts are present, each one can be specifically targeted using the host selector e.g `:host(.my-chart-class)`.
 * 5. Import the theme file.
 *
 *
 * ### Example: Two Charts with a Red Title but only one with a Blue Subtitle
 *
 * ```html
 * <link rel="import" href="shared-styles.html">
 * ...
 * <vaadin-chart title="Red Title" subtitle="Not Styled">
 *   <vaadin-chart-series values="[19,12,9,24,5]"></vaadin-chart-series>
 * </vaadin-chart>
 *
 * <vaadin-chart class="blue-subtitle" title="Red Title" subtitle="Blue Subtitle">
 *   <vaadin-chart-series values="[19,12,9,24,5]"></vaadin-chart-series>
 * </vaadin-chart>
 * ```
 *
 * shared-styles.html
 *
 * ```html
 * <link rel="import" href="../bower_components/vaadin-charts/theme/vaadin-chart-default-theme.html">
 *
 * <dom-module id="css-style-example" theme-for="vaadin-chart">
 *    <template>
 *      <style include="vaadin-chart-default-theme">
 *        .highcharts-title {
 *          fill: red;
 *          font-size: xx-large;
 *        }
 *
 *        :host(.blue-subtitle) .highcharts-subtitle {
 *          fill: blue;
 *        }
 *      </style>
 *    </template>
 * </dom-module>
 * ```
 *
 * ### RTL support
 *
 * `vaadin-charts` as well as [Highcharts](https://www.highcharts.com/) by itself are not adjusting the layout
 * based on the `dir` attribute. In order to make `vaadin-charts` display RTL content properly additional
 * JSON configuration should be used.
 * Each chart should be updated based on the specific needs, but general recommendations are:
 *
 *  1. Set `reversed` to true for xAxis (https://api.highcharts.com/highcharts/xAxis.reversed).
 *  2. Set `useHTML` to true for text elements, i.e. `tooltip` (https://api.highcharts.com/highcharts/tooltip.useHTML).
 *  3. Set `rtl` to true for `legend` (https://api.highcharts.com/highcharts/legend.rtl).
 *
 * Using as a base the project created with in Quick Start and an `additionalOptions` in order to make RTL adjustments:
 *
 * ```html
 *  <vaadin-chart title="۱- عنوان نمودار" subtitle="۲- عنوان فرعی نمودار"
 *    additional-options='{"title": {"useHTML": true}, "tooltip": {"useHTML": true}, "subtitle": {"useHTML": true},
 *    "legend": {"rtl": true}, "yAxis": [{"id": "۴- مقادیر", "title": {"text": "۴- مقادیر", "useHTML": true}}],
 *    "xAxis": {"reversed": true}}'>
 *    <vaadin-chart-series
 *          type= "column"
 *          title="۳- عنوان ردیف"
 *          unit="۴- مقادیر"
 *          values="[10,20,30]">
 *    </vaadin-chart-series>
 *  </vaadin-chart>
 * ```
 *
 * ### Setting colors
 *
 * Although charts can be styled as described above, there is a simpler way for setting colors.
 * Colors can be set using CSS custom properties `--vaadin-charts-color-{n}` (where `n` goes from `0 - 9`).
 *
 * For example `--vaadin-charts-color-0` sets the color of the first series on a chart.
 *
 * ### Validating your License
 *
 * When using Vaadin Charts in a development environment, you will see a pop-up that asks you
 * to validate your license by signing in to vaadin.com.
 */
declare class ChartElement extends
  ThemableMixin(
  ElementMixin(
  PolymerElement)) {
  readonly options: Options;

  /**
   * Configuration object that exposes the JS Api to configure the chart.
   *
   * Most important methods are:
   * - `addSeries (Object options, [Boolean redraw], [Mixed animation])`
   * - `addAxis (Object options, [Boolean isX], [Boolean redraw], [Mixed animation])`
   * - `setTitle (Object title, object subtitle, Boolean redraw)`
   *
   * Most important properties are:
   * - `configuration.series`: An array of the chart's series. Detailed API for Series object is
   *     available in [API Site](http://api.highcharts.com/class-reference/Highcharts.Series)
   * - `configuration.xAxis`: An array of the chart's x axes. Detailed API for Axis object is
   *     available in [API Site](http://api.highcharts.com/class-reference/Highcharts.Axis)
   * - `configuration.yAxis`: An array of the chart's y axes. Detailed API for Axis object is
   *     available in [API Site](http://api.highcharts.com/class-reference/Highcharts.Axis)
   * - `configuration.title`: The chart title.
   *
   * For detailed documentation of available API check the [API site](http://api.highcharts.com/class-reference/classes.list)
   */
  configuration: Chart|undefined;

  /**
   * If categories are present names are used instead of numbers for the category axis.
   * The format of categories can be an `Array` with a list of categories, such as `['2010', '2011', '2012']`
   * or a mapping `Object`, like `{0:'1',9:'Target (10)', 15: 'Max'}`.
   */
  categories: ChartCategories|null|undefined;

  /**
   * Category-axis maximum value. Defaults to `undefined`.
   * @attr {number} category-max
   */
  categoryMax: number|null|undefined;

  /**
   * Category-axis minimum value. Defaults to `undefined`.
   * @attr {number} category-min
   */
  categoryMin: number|null|undefined;

  /**
   * The position of the category axis. Acceptable values are `left`, `right`, `top` and `bottom`
   * except for bar charts which only accept `left` and `right`.
   * With the default value, charts appear as though they have `category-position="bottom"`
   * except for bar charts that appear as though they have `category-position="left"`.
   *
   * Defaults to `undefined`
   * @attr {left|right|top|bottom} category-position
   */
  categoryPosition: ChartCategoryPosition|null|undefined;

  /**
   * Specifies whether to hide legend or show.
   * Legend configuration can be set up via additionalOptions property
   * @attr {boolean} no-legend
   */
  noLegend: boolean|null|undefined;

  /**
   * Specifies how series are stacked on top of each other.
   * Possible values are null, "normal" or "percent".
   * If "stack" property is not defined on the vaadin-chart-series elements, then series will be put into
   * the default stack.
   * @attr {normal|percent} stacking
   */
  stacking: ChartStacking|null|undefined;

  /**
   * Specifies whether the chart is a normal chart or a timeline chart.
   */
  timeline: boolean|null|undefined;

  /**
   * Represents the title of the chart.
   */
  title: string;

  /**
   * Whether or not to show tooltip when hovering data points.
   */
  tooltip: boolean|null|undefined;

  /**
   * Sets the default series type of the chart.
   * Note that `'bar'`, `'gauge'` and `'solidgauge'` should be set as default series type.
   */
  type: string|null|undefined;

  /**
   * Represents the subtitle of the chart.
   */
  subtitle: string|undefined;

  /**
   * Specifies whether to show chart in 3 or in 2 dimensions.
   * Some display angles are added by default to the "chart.options3d" (`{alpha: 15, beta: 15, depth: 50}`).
   * 3D display options can be modified via `additionalOptions`.
   * The thickness of a Pie chart can be set on `additionalOptions` through `plotOptions.pie.depth`.
   * 3D is supported by Bar, Column, Pie and Scatter3D charts.
   * More info available at [Highcharts](https://www.highcharts.com/docs/chart-concepts/3d-charts).
   */
  chart3d: boolean|null|undefined;

  /**
   * Specifies the message displayed on a chart without displayable data.
   * @attr {string} empty-text
   */
  emptyText: string;

  /**
   * Represents additional JSON configuration.
   */
  additionalOptions: Options|null|undefined;

  /**
   * When present, cartesian charts like line, spline, area and column are transformed
   * into the polar coordinate system.
   */
  polar: boolean|null|undefined;
  static _finalizeClass(): void;
  connectedCallback(): void;
  disconnectedCallback(): void;

  /**
   * Search for axis with given `id`.
   *
   * @param id contains the id that will be searched
   * @param isXAxis indicates if it will remove x or y axes. Defaults to `false`.
   */
  __getAxis(id: string, isXAxis: boolean): Axis|null;

  /**
   * Add an axis with given options
   *
   * @param options axis options
   * @param isXAxis indicates if axis is X (`true`) or Y (`false`). Defaults to `false`.
   */
  __addAxis(options: object|null, isXAxis: boolean): Axis;

  /**
   * Iterates over axes (y or x) and removes whenever it doesn't contain any series and was created for unit
   *
   * @param isXAxis indicates if it will remove x or y axes. Defaults to `false`.
   */
  __removeAxisIfEmpty(isXAxis: boolean): void;

  /**
   * Update the chart configuration.
   * This JSON API provides a simple single-argument alternative to the configuration property.
   *
   * Styling properties specified in this configuration will be ignored. To learn about chart styling
   * please see the CSS Styling section above.
   *
   * @param jsonConfiguration Object chart configuration. Most important properties are:
   *
   * - chart `Object` with options regarding the chart area and plot area as well as general chart options.
   *    Detailed API for chart object is available in [API Site](http://api.highcharts.com/highcharts/chart)
   * - credits `Object` with options regarding the chart area and plot area as well as general chart options.
   *    Detailed API for credits object is available in [API Site](http://api.highcharts.com/highcharts/credits)
   * - labels `Object[]` with HTML labels that can be positioned anywhere in the chart area
   *    Detailed API for labels object is available in [API Site](http://api.highcharts.com/highcharts/labels)
   * - plotOptions `Object` wrapper for config objects for each series type.
   *    Detailed API for plotOptions object is available in [API Site](http://api.highcharts.com/highcharts/plotOptions)
   * - series `Object[]` the actual series to append to the chart.
   *    Detailed API for series object is available in [API Site](http://api.highcharts.com/highcharts/series)
   * - subtitle `Object` the chart's subtitle.
   *    Detailed API for subtitle object is available in [API Site](http://api.highcharts.com/highcharts/subtitle)
   * - title `Object` the chart's main title.
   *    Detailed API for title object is available in [API Site](http://api.highcharts.com/highcharts/title)
   * - tooltip `Object` Options for the tooltip that appears when the user hovers over a series or point.
   *    Detailed API for tooltip object is available in [API Site](http://api.highcharts.com/highcharts/tooltip)
   * - xAxis `Object[]` The X axis or category axis. Normally this is the horizontal axis.
   *    Detailed API for xAxis object is available in [API Site](http://api.highcharts.com/highcharts/xAxis)
   * - yAxis `Object[]` The Y axis or value axis. Normally this is the vertical axis.
   *    Detailed API for yAxis object is available in [API Site](http://api.highcharts.com/highcharts/yAxis)
   * - zAxis `Object[]` The Z axis or depth axis for 3D plots.
   *    Detailed API for zAxis object is available in [API Site](http://api.highcharts.com/highcharts/zAxis)
   * @param resetConfiguration Optional boolean that should be set to true if no other chart configuration was set before or
   *    if existing configuration should be discarded.
   */
  update(jsonConfiguration: Options, resetConfiguration?: boolean): void;
}

declare global {

  interface HTMLElementTagNameMap {
    "vaadin-chart": ChartElement;
  }
}

export {ChartElement};

import {Options} from 'highcharts';

import {Chart} from 'highcharts';

import {ChartCategories} from '../@types/interfaces';

import {ChartCategoryPosition} from '../@types/interfaces';

import {ChartStacking} from '../@types/interfaces';

import {Axis} from 'highcharts';
